export default {
	LOAD_VIDEOS_SUCCESS: "LOAD_VIDEOS_SUCCESS",
	LOAD_VIDEOS_FAILURE: "LOAD_VIDEOS_FAILURE",
	SET_VIDEOS_LOADING: "SET_VIDEOS_LOADING",

	LOAD_VIDEO_SUCCESS: "LOAD_VIDEO_SUCCESS",
	LOAD_VIDEO_FAILURE: "LOAD_VIDEO_FAILURE",
	SET_VIDEO_LOADING: "SET_VIDEO_LOADING",

	SAVE_TASK_VIDEO_SUCCESS: "SAVE_TASK_VIDEO_SUCCESS",
	SAVE_TASK_VIDEO_FAILURE: "SAVE_TASK_VIDEO_FAILURE",
	SET_SAVE_TASK_VIDEO_LOADING: "SET_SAVE_TASK_VIDEO_LOADING",

	DELETE_TASK_VIDEO_SUCCESS: "DELETE_TASK_VIDEO_SUCCESS",
	DELETE_TASK_VIDEO_FAILURE: "DELETE_TASK_VIDEO_FAILURE",

	REPLACE_TASK_VIDEO_SUCCESS: "REPLACE_TASK_VIDEO_SUCCESS",
	REPLACE_TASK_VIDEO_FAILURE: "REPLACE_TASK_VIDEO_FAILURE",

	CLEAR_VIDEOS_SUCCESS: "CLEAR_VIDEOS_SUCCESS",
	CLEAR_VIDEO_SUCCESS: "CLEAR_VIDEO_SUCCESS"
};
